name: CPU tests

on:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: pip
    - name: Detect Docker changes
      id: changes
      uses: dorny/paths-filter@v3
      with:
        filters: |
          docker:
            - 'dockerfiles/Dockerfile.sandbox'
            - 'dockerfiles/Dockerfile.nemo-skills'
            - 'nemo_skills/code_execution/local_sandbox/**'
            - 'requirements/**'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
    - name: Build Images
      if: steps.changes.outputs.docker == 'true'
      run: |
        # these tags need to match the ones in tests/gpu-tests/test-local.yaml
        docker build -t igitman/nemo-skills:0.7.0 -f dockerfiles/Dockerfile.nemo-skills .
        docker build -t igitman/nemo-skills-sandbox:0.7.1 -f dockerfiles/Dockerfile.sandbox .
    - name: Pull Images
      if: steps.changes.outputs.docker != 'true'
      run: |
        docker pull igitman/nemo-skills:0.7.0
        docker pull igitman/nemo-skills-sandbox:0.7.1
    - name: Run all tests
      env:
        NVIDIA_API_KEY: ${{ secrets.NVIDIA_API_KEY }}
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        docker run --rm --network=host igitman/nemo-skills-sandbox:0.7.1 &
        sleep 10
        set -o pipefail # this will make sure next line returns non-0 exit code if tests fail
        ns prepare_data gsm8k math-500
        python -m pytest tests/ -m "not gpu" --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=nemo_skills --cov=pipeline --durations=30 -rs -s -vvv
